### ISSUE TITLE
Support for TLS 1.3

### ISSUE THREAD

**Issue by mildsunrise** [kolontsov/node-sslkeylog#4]
Starting with Node 11.10 (I think), Node.JS supports making TLS1.3 connections:
https://github.com/nodejs/node/commit/7393e37af1 (commit on v11.x)
https://github.com/nodejs/node/commit/42dbaed460 (commit on v12.x)

Info on TLS 1.3 secrets and how Wireshark decrypts them:
https://security.stackexchange.com/a/42350/5067 (would be nice adding to README)

All this means:
- The API changes, we should use `session` event if Node >= 11.10 is detected, instead of `secureConnection` or `secureConnect`.
- We should log secrets in a different format.

I'll try to work on this.

**Comment by kolontsov** [comment]
Thanks! It would be nice to support TLS 1.3 properly. I do have plans to work on it, but I didn't touched it yet, so any PRs/suggestions are welcome.

**Comment by kolontsov** [comment]
Reference: [NodeJS/OpenSSL versions](https://github.com/kolontsov/node-sslkeylog/pull/2#issuecomment-490483501) (from merged PR)

**Comment by mildsunrise** [comment]
Tracking nodejs/node#27419 for TLSv1.3 / keylog support in v10.

**Comment by mildsunrise** [comment]
I have [started working](https://github.com/nodejs/node/commit/93589aa393627e22efce0c936615ffb51ce0925f?short_path=f6e3a86#diff-f6e3a86962eaf0897ab59e88b418e64f) on a PR to Node.JS, which exports the SSL_CTX_set_keylog_callback API as a `keylog` event which is emitted with the line of text.

So for instance:

~~~ js
const req = https.request("https://example.org")
req.on("socket", socket => {
  socket.on("keylog", console.log)
})
~~~

![Screenshot from 2019-05-11 12 45 41](https://user-images.githubusercontent.com/1177304/57568654-c10e6b80-73ea-11e9-9785-391253edfb90.png)

If it's accepted in Node.JS, we could then polyfill this API for older versions(?)

**Comment by kolontsov** [comment]
> I have started working on a PR to Node.JS, which exports the SSL_CTX_set_keylog_callback API as a keylog event which is emitted with the line of text.

Very cool! This is a very right thing to do, good luck with that.

> If it's accepted in Node.JS, we could then polyfill this API for older versions(?)

Agree. This implementation with events and handlers looks natural and flexible.

**Comment by mildsunrise** [comment]
Pull request created: nodejs/node#27654

**Comment by kolontsov** [comment]
Wow, it was fast. Nice work!

**Comment by mildsunrise** [comment]
It just landed on Node.JS :confetti_ball: It was faster than I expected... I'm working on a polyfill for the API, do you think we could include it in this version?

**Comment by kolontsov** [comment]
Congratulations! 

> I'm working on a polyfill for the API, do you think we could include it in this version?

Yes. It would be great.

**Comment by mildsunrise** [comment]
Update: Node v12.3.0 was just released with the keylog API :sparkles:

**Comment by mildsunrise** [comment]
In reference to https://github.com/kolontsov/node-sslkeylog/issues/4#issuecomment-491494903, Node v10.16.0 was released 3 days ago, and it includes OpenSSL 1.1.1b, so keylog is available.

However it seems I misunderstood, TLSv1.3 has not been backported.
In fact, an exception is thrown if you attempt to use it (that's why https://github.com/kolontsov/node-sslkeylog/commit/3060046aaa4ebd9a01b01347160877cf611af4c9 failed CI).

**Comment by mildsunrise** [comment]
I'll modify the tests to detect that exception and skip the test in that case.

**Comment by kolontsov** [comment]
Currently, I just skip TLS 1.3 test on Nodejs <11 (https://github.com/kolontsov/node-sslkeylog/commit/b47ba919e79a6da40449db40fb0023483fbe4445), so it's not issue :)

**Comment by mildsunrise** [comment]
True! But I'd prefer to mark the test as skipped, rather than not registering it at all :thinking:

**Comment by kolontsov** [comment]
It makes sense. I agree.

**Comment by mildsunrise** [comment]
We can close this now (unless I'm missing something)
